name: MCExperience
version: '1.0-SNAPSHOT'
main: me.stormtrooper.mcexperience.MCExperience
api-version: 1.18
commands:
  mark-location:
    description: will make a 50 block tall tower
    usage: /<command>
    aliases: [mark, tower]
  unlimited-wither-spawner:
    description: will spawn a lot of withers
    usage: /<command> <initdelay> <spawndelay>
    aliases: [wither]